### ISSUE TITLE
When debug mode is enabled, the edit comment modal window won't show

### ISSUE THREAD

**Issue by Chaosmeister** [creecros/MarkdownPlus#1]
see https://github.com/kanboard/kanboard/issues/4475

**Comment by creecros** [comment]
My guess would be the "autocomplete" is interfering. I'd have to test. This plugin is pretty much an injection of other vendor software that my little brain would never understand. 

I could look at adding an option to turn off the autocomplete, which may solve the issue, if that is the issue.

**Comment by Chaosmeister** [comment]
I'm not a php developer myself, so I might not be helpful in this case as well.  
It would just be nice if debug mode was possible with the plugin active.  
No problem if you're not able to fix this, maybe someone sometime will be 😅

**Comment by creecros** [comment]
im only guessing it is fixed, because it did not do it for me, tested with debug on and was able to edit comments no problem.

**Comment by Chaosmeister** [comment]
It was a really Old Ticket. I think I couldn't even reproduce it myself anymore since I started developing plugins.
