### ISSUE TITLE
URL syntax is broken on lines with checkboxes

### ISSUE THREAD

**Issue by 11mariom** [creecros/MarkdownPlus#10]
With the snippet below, each line containing a link is broken when there is a checkbox on that line.

```markdown
Text [Google this](https://google.com/)

- List [Google list](https://google.com/)
- [ ] List checkbox [Google checkbox](https://google.com/)

[ ] Checkbox [Google checkbox](https://google.com/)
```

![obraz](https://user-images.githubusercontent.com/552506/219029612-1397cf4a-7b09-4a97-93fc-702f98f6e609.png)

**Comment by Chaosmeister** [comment]
can confirm,  we ran into this just yesterday
