### ISSUE TITLE
Version 1.1.4 completely broken ⚠️️

### ISSUE THREAD

**Issue by RainerBielefeld** [creecros/MarkdownPlus#23]
At least for my KANBOARD installation.

[For details please see Plugin "MarkdownPLUS 1.1.4" will not update, is completely broken ⚠️️](https://kanboard.discourse.group/t/plugin-markdownplus-1-1-4-will-not-update-is-completely-broken/2983)

**Comment by Chaosmeister** [comment]
heyo,
thanks for the report

The zip file got packed incorrectly. I just fixed it.

please try again

**Comment by RainerBielefeld** [comment]
I did some tests whether works:  
* 👍 Install *MarkdownPlus* via *PluginManager*  
* 👍 Checkboxes   
* 👍 Some html in KANBOARD comment  
  
Seems that problems have become resolved.
