### ISSUE TITLE
Plugin not working with version v1.2.37 (latest)

### ISSUE THREAD

**Issue by Wc4ever** [creecros/MarkdownPlus#29]
When I open task description page formatting looks incorrect. Also error appears in log `[error] 14#14: *68 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Error: Call to undefined method Kanboard\Plugin\MarkdownPlus\Helper\MarkdownPlusHelper::reply() in /var/www/app/app/Template/comment/show.php:65`

Configuration
Application version: v1.2.37
PHP version: 8.3.7
PHP SAPI: fpm-fcgi
HTTP Client: cURL
OS version: Linux 5.4.0-187-generic
Database driver: mysql
Database version: 11.4.2-MariaDB-ubu2404
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36

**Comment by creecros** [comment]
Try using the master repo

#28
