### ISSUE TITLE
Checkbox parser removes mentions and internal links

### ISSUE THREAD

**Issue by tomaszstrojny** [creecros/MarkdownPlus#3]
After installing the plugin, all the comments and descriptions are cleared from the internal links and @mentions. 

I've tracked down it's because of the `ParsedownCheckbox`, emojis work fine.

My current code for the `MarkdownPlusHelper->markdown()` looks like this, and it works:

```php
    public function markdown($text, $isPublicLink = false)
    {
        $emoji = new Client(new Ruleset());
        $parser = new Markdown($this->container, $isPublicLink);
        $parsecheckbox = new ParsedownCheckbox();
        if ($this->configModel->get('unicode_shortcode', '2') == 1) {
            $text = $emoji->shortnameToUnicode($text);
        } else {
            $text = $emoji->toImage($text);
        }

        // $parser->setMarkupEscaped(MARKDOWN_ESCAPE_HTML);
        $text = $parser->text($text);
        // $text = $parsecheckbox->text($text);

        return $text;
    }
```

While I try to add the `parsecheckbox`  in any other place, it's escaping the links. It generally makes sense, but I would like to have both of them and don't know how to touch it. Do you have any suggestions?

**Comment by creecros** [comment]
anyway you could include a screenshot or gif showing me the issue? it's been a long time since I really used kanboard so not sure I even know what you're talking about. point me in the right direction.

**Comment by tomaszstrojny** [comment]
Sure! Thanks for the response :)

For the code I've pasted above I am getting such a content:
![image](https://user-images.githubusercontent.com/8854428/111001316-d906fb80-8383-11eb-9800-8029d90ef897.png)

When I comment the `$text = $parser->text($text);` and uncomment the `// $text = $parsecheckbox->text($text);` I'm getting something like this:
![image](https://user-images.githubusercontent.com/8854428/111001374-f63bca00-8383-11eb-8a56-d933d48616a4.png)

As you can see, the checkbox is rendered correctly, but the links under `@admin` and `#1` disappeared.

**Comment by creecros** [comment]
OK, I understand now.

and what's the non preview of that link code look like?

is it markdown or html?

**Comment by creecros** [comment]
nm I see it autofills... I'll take a look, probably some js stuff goin on with that, I wasn't even aware of it.

**Comment by tomaszstrojny** [comment]
From what I observe, it's in PHP. 

The methods meant to build the internal link and users (defined in the `Core/Kanboard`) are not run when we use the checkbox parser. I'm tracing the execution with xdebug and it just doesn't run it. It's like the `Core/Markdown` parser runs or the `ParsedownCheckbox` - I cannot get both of them working on the same content.

**Comment by tomaszstrojny** [comment]
> OK, I understand now.
> 
> and what's the non preview of that link code look like?
> 
> is it markdown or html? or does it just link with `#1` oh and the `@`

Generally in Kanboard internal links are created by the core parser, which looks for @ and #, give suggestions and then parse them as links. @mentions to users and #123 to tasks.

For the not parsed version HTML looks like that:

```html
<article class="markdown">
    <p>test @admin <img class="emojione" alt="↕" title=":arrow_up_down:" src="https://cdn.jsdelivr.net/emojione/assets/4.5/png/32/2195.png"> #1 </p>
    <input type="checkbox" disabled=""> ates        
</article>
```

on the other hand we have this:

```html
<article class="markdown">
    <p>test <a href="/?controller=UserViewController&amp;action=profile&amp;user_id=1" class="user-mention-link" title="admin" aria-label="admin">@admin</a> <img class="emojione" alt="↕" title=":arrow_up_down:" src="https://cdn.jsdelivr.net/emojione/assets/4.5/png/32/2195.png"> <a href="/?controller=TaskViewController&amp;action=show&amp;task_id=1">#1</a>
    </p>
    <p>[ ] ates</p>        
</article>
```

**Comment by creecros** [comment]
see, you know more than I do! I'll definitely take a look and see what I can come up with, might just take me a while to get the chance though. if I'm lucky, you solve it before me 😄

**Comment by creecros** [comment]
i figured out whats going on. had to come up with a workaround, but long story short, the core markdown extends Parsedown, i had to back it out and extend ParsedownCheckbox, which extends Parsedown extra, and then add to the construct to get it to run them all.


![image](https://user-images.githubusercontent.com/26339368/111164357-65781080-8574-11eb-872a-d85e4ddf5456.png)

**Comment by creecros** [comment]
@tomaszstrojny givee it a test drive, hopefully i didn't screw anything up fixing it

**Comment by creecros** [comment]
well, now i'm getting an error, and I'm out of time for the day. to be continued:
`#0 /var/www/app/app/Template/task/description.php(5): Kanboard\Plugin\MarkdownPlus\Helper\MarkdownPlusHelper->markdown(),
#1 /var/www/app/app/Core/Template.php(83): include('/var/www/app/ap...'),
#2 /var/www/app/app/Template/task/show.php(11): Kanboard\Core\Template->render(),
#3 /var/www/app/app/Core/Template.php(83): include('/var/www/app/ap...'),
#4 /var/www/app/app/Helper/LayoutHelper.php(207): Kanboard\Core\Template->render(),
#5 /var/www/app/app/Helper/LayoutHelper.php(74): Kanboard\Helper\LayoutHelper->subLayout(),
#6 /var/www/app/app/Controller/TaskViewController.php(77): Kanboard\Helper\LayoutHelper->task(),
#7 /var/www/app/app/Core/Controller/Runner.php(77): Kanboard\Controller\TaskViewController->show(),
#8 /var/www/app/app/Core/Controller/Runner.php(31): Kanboard\Core\Controller\Runner->executeController(),
#9 /v" while reading response header from upstream, client: 172.17.0.3, server: localhost, request: "GET /project/4/task/110 HTTP/1.1", upstream: "fastcgi://unix:/var/run/php-fpm.sock:", host: "projects.divdist.com",
[15-Mar-2021 13:49:19 UTC] PHP Warning:  Module 'fileinfo' already loaded in Unknown on line 0,
PHP message: PHP Notice:  Undefined variable: parser in /var/www/app/plugins/MarkdownPlus/Helper/MarkdownPlusHelper.php on line 62",
PHP message: PHP Fatal error:  Uncaught Error: Call to a member function setMarkupEscaped() on null in /var/www/app/plugins/MarkdownPlus/Helper/MarkdownPlusHelper.php:62",
Stack trace:",
#0 /var/www/app/app/Template/task/description.php(5): Kanboard\Plugin\MarkdownPlus\Helper\MarkdownPlusHelper->markdown()",
#1 /var/www/app/app/Core/Template.php(83): include('/var/www/app/ap...')",
#2 /var/www/app/app/Template/task/show.php(11): Kanboard\Core\Template->render()",
#3 /var/www/app/app/Core/Template.php(83): include('/var/www/app/ap...')",
#4 /var/www/app/app/Helper/LayoutHelper.php(207): Kanboard\Core\Template->render()",
#5 /var/www/app/app/Helper/LayoutHelper.php(74): Kanboard\Helper\LayoutHelper->subLayout()",
#6 /var/www/app/app/Controller/TaskViewController.php(77): Kanboard\Helper\LayoutHelper->task()",
#7 /var/www/app/app/Core/Controller/Runner.php(77): Kanboard\Controller\TaskViewController->show()",
#8 /var/www/app/app/Core/Controller/Runner.php(31): Kanboard\Core\Controller\Runner->executeController()",
#9 /var/www/app...",
2021/03/15 13:49:21 [error] 16#16: *1 FastCGI sent in stderr: "PHP message: PHP Notice:  Undefined variable: parser in /var/www/app/plugins/MarkdownPlus/Helper/MarkdownPlusHelper.php on line 62PHP message: PHP Fatal error:  Uncaught Error: Call to a member function setMarkupEscaped() on null in /var/www/app/plugins/MarkdownPlus/Helper/MarkdownPlusHelper.php:62,
Stack trace:,
#0 /var/www/app/app/Template/task/description.php(5): Kanboard\Plugin\MarkdownPlus\Helper\MarkdownPlusHelper->markdown(),
#1 /var/www/app/app/Core/Template.php(83): include('/var/www/app/ap...'),
#2 /var/www/app/app/Template/task/show.php(11): Kanboard\Core\Template->render(),
#3 /var/www/app/app/Core/Template.php(83): include('/var/www/app/ap...'),
#4 /var/www/app/app/Helper/LayoutHelper.php(207): Kanboard\Core\Template->render(),
#5 /var/www/app/app/Helper/LayoutHelper.php(74): Kanboard\Helper\LayoutHelper->subLayout(),
#6 /var/www/app/app/Controller/TaskViewController.php(77): Kanboard\Helper\LayoutHelper->task(),
#7 /var/www/app/app/Core/Controller/Runner.php(77): Kanboard\Controller\TaskViewController->show(),
#8 /var/www/app/app/Core/Controller/Runner.php(31): Kanboard\Core\Controller\Runner->executeController(),
#9 /var/www/app" while reading response header from upstream, client: 172.17.0.3, server: localhost, request: "GET /project/4/task/110 HTTP/1.1", upstream: "fastcgi://unix:/var/run/php-fpm.sock:", host: "projects.divdist.com",
[15-Mar-2021 13:49:59 UTC] PHP Warning:  Module 'fileinfo' already loaded in Unknown on line 0,
PHP message: PHP Notice:  Trying to access array offset on value of type null in /var/www/app/plugins/MarkdownPlus/vendor/erusev/parsedown-extra/ParsedownExtra.php on line 241",
PHP message: PHP Notice:  Trying to access array offset on value of type null in /var/www/app/plugins/MarkdownPlus/vendor/erusev/parsedown-extra/ParsedownExtra.php on line 241",
2021/03/15 13:50:01 [error] 16#16: *1 FastCGI sent in stderr: "PHP message: PHP Notice:  Trying to access array offset on value of type null in /var/www/app/plugins/MarkdownPlus/vendor/erusev/parsedown-extra/ParsedownExtra.php on line 241PHP message: PHP Notice:  Trying to access array offset on value of type null in /var/www/app/plugins/MarkdownPlus/vendor/erusev/parsedown-extra/ParsedownExtra.php on line 241" while reading response header from upstream, client: 172.17.0.3, server: localhost, request: "GET /project/4/task/110 HTTP/1.1", upstream: "fastcgi://unix:/var/run/php-fpm.sock:", host: "projects.divdist.com",
[15-Mar-2021 13:50:22 UTC] PHP Warning:  Module 'fileinfo' already loaded in Unknown on line 0,
PHP message: PHP Fatal error:  Uncaught ArgumentCountError: Too few arguments to function Kanboard\Plugin\MarkdownPlus\Helper\CoreMarkdown::__construct(), 0 passed in /var/www/app/plugins/MarkdownPlus/Helper/MarkdownPlusHelper.php on line 61 and exactly 2 expected in /var/www/app/plugins/MarkdownPlus/Helper/CoreMarkdown.php:40",
Stack trace:",
#0 /var/www/app/plugins/MarkdownPlus/Helper/MarkdownPlusHelper.php(61): Kanboard\Plugin\MarkdownPlus\Helper\CoreMarkdown->__construct()",
#1 /var/www/app/app/Template/task/description.php(5): Kanboard\Plugin\MarkdownPlus\Helper\MarkdownPlusHelper->markdown()",
#2 /var/www/app/app/Core/Template.php(83): include('/var/www/app/ap...')",
#3 /var/www/app/app/Template/task/show.php(11): Kanboard\Core\Template->render()",
#4 /var/www/app/app/Core/Template.php(83): include('/var/www/app/ap...')",
#5 /var/www/app/app/Helper/LayoutHelper.php(207): Kanboard\Core\Template->render()",
#6 /var/www/app/app/Helper/LayoutHelper.php(74): Kanboard\Helper\LayoutHelper->subLayout()",
#7 /var/www/app/app/...",
2021/03/15 13:50:24 [error] 16#16: *1 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught ArgumentCountError: Too few arguments to function Kanboard\Plugin\MarkdownPlus\Helper\CoreMarkdown::__construct(), 0 passed in /var/www/app/plugins/MarkdownPlus/Helper/MarkdownPlusHelper.php on line 61 and exactly 2 expected in /var/www/app/plugins/MarkdownPlus/Helper/CoreMarkdown.php:40,
Stack trace:,
#0 /var/www/app/plugins/MarkdownPlus/Helper/MarkdownPlusHelper.php(61): Kanboard\Plugin\MarkdownPlus\Helper\CoreMarkdown->__construct(),
#1 /var/www/app/app/Template/task/description.php(5): Kanboard\Plugin\MarkdownPlus\Helper\MarkdownPlusHelper->markdown(),
#2 /var/www/app/app/Core/Template.php(83): include('/var/www/app/ap...'),
#3 /var/www/app/app/Template/task/show.php(11): Kanboard\Core\Template->render(),
#4 /var/www/app/app/Core/Template.php(83): include('/var/www/app/ap...'),
#5 /var/www/app/app/Helper/LayoutHelper.php(207): Kanboard\Core\Template->render(),
#6 /var/www/app/app/Helper/LayoutHelper.php(74): Kanboard\Helper\LayoutHelper->subLayout(),
#7 /var/www/app/app/" while reading response header from upstream, client: 172.17.0.3, server: localhost, request: "GET /project/4/task/110 HTTP/1.1", upstream: "fastcgi://unix:/var/run/php-fpm.sock:", host: "projects.divdist.com",
[15-Mar-2021 13:51:12 UTC] PHP Warning:  Module 'fileinfo' already loaded in Unknown on line 0,
PHP message: PHP Fatal error:  Uncaught TypeError: Argument 1 passed to Kanboard\Plugin\MarkdownPlus\Helper\CoreMarkdown::__construct() must be an instance of Pimple\Container, string given, called in /var/www/app/plugins/MarkdownPlus/Helper/MarkdownPlusHelper.php on line 61 and defined in /var/www/app/plugins/MarkdownPlus/Helper/CoreMarkdown.php:40",
Stack trace:",
#0 /var/www/app/plugins/MarkdownPlus/Helper/MarkdownPlusHelper.php(61): Kanboard\Plugin\MarkdownPlus\Helper\CoreMarkdown->__construct()",
#1 /var/www/app/app/Template/task/description.php(5): Kanboard\Plugin\MarkdownPlus\Helper\MarkdownPlusHelper->markdown()",
#2 /var/www/app/app/Core/Template.php(83): include('/var/www/app/ap...')",
#3 /var/www/app/app/Template/task/show.php(11): Kanboard\Core\Template->render()",
#4 /var/www/app/app/Core/Template.php(83): include('/var/www/app/ap...')",
#5 /var/www/app/app/Helper/LayoutHelper.php(207): Kanboard\Core\Template->render()",
#6 /var/www/app/app/Helper/LayoutHelper.php(74): Kanboard\Helper\LayoutHelper->subLayout...",
2021/03/15 13:51:15 [error] 16#16: *1 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught TypeError: Argument 1 passed to Kanboard\Plugin\MarkdownPlus\Helper\CoreMarkdown::__construct() must be an instance of Pimple\Container, string given, called in /var/www/app/plugins/MarkdownPlus/Helper/MarkdownPlusHelper.php on line 61 and defined in /var/www/app/plugins/MarkdownPlus/Helper/CoreMarkdown.php:40,
Stack trace:,
#0 /var/www/app/plugins/MarkdownPlus/Helper/MarkdownPlusHelper.php(61): Kanboard\Plugin\MarkdownPlus\Helper\CoreMarkdown->__construct(),
#1 /var/www/app/app/Template/task/description.php(5): Kanboard\Plugin\MarkdownPlus\Helper\MarkdownPlusHelper->markdown(),
#2 /var/www/app/app/Core/Template.php(83): include('/var/www/app/ap...'),
#3 /var/www/app/app/Template/task/show.php(11): Kanboard\Core\Template->render(),
#4 /var/www/app/app/Core/Template.php(83): include('/var/www/app/ap...'),
#5 /var/www/app/app/Helper/LayoutHelper.php(207): Kanboard\Core\Template->render(),
#6 /var/www/app/app/Helper/LayoutHelper.php(74): Kanboard\Helper\LayoutHelper->subLayout" while reading response header from upstream, client: 172.17.0.3, server: localhost, request: "GET /project/4/task/110 HTTP/1.1", upstream: "fastcgi://unix:/var/run/php-fpm.sock:", host: "projects.divdist.com",
[15-Mar-2021 13:51:55 UTC] PHP Warning:  Module 'fileinfo' already loaded in Unknown on line 0,
PHP message: PHP Notice:  Trying to access array offset on value of type null in /var/www/app/plugins/MarkdownPlus/vendor/erusev/parsedown-extra/ParsedownExtra.php on line 305",
PHP message: PHP Notice:  Trying to access array offset on value of type null in /var/www/app/plugins/MarkdownPlus/vendor/erusev/parsedown-extra/ParsedownExtra.php on line 305",
PHP message: PHP Notice:  Trying to access array offset on value of type null in /var/www/app/plugins/MarkdownPlus/vendor/erusev/parsedown-extra/ParsedownExtra.php on line 241",
PHP message: PHP Notice:  Trying to access array offset on value of type null in /var/www/app/plugins/MarkdownPlus/vendor/erusev/parsedown-extra/ParsedownExtra.php on line 241",
PHP message: PHP Notice:  Trying to access array offset on value of type null in /var/www/app/plugins/MarkdownPlus/vendor/erusev/parsedown-extra/ParsedownExtra.php on line 305",
2021/03/15 13:51:56 [error] 16#16: *1 FastCGI sent in stderr: "PHP message: PHP Notice:  Trying to access array offset on value of type null in /var/www/app/plugins/MarkdownPlus/vendor/erusev/parsedown-extra/ParsedownExtra.php on line 305PHP message: PHP Notice:  Trying to access array offset on value of type null in /var/www/app/plugins/MarkdownPlus/vendor/erusev/parsedown-extra/ParsedownExtra.php on line 305PHP message: PHP Notice:  Trying to access array offset on value of type null in /var/www/app/plugins/MarkdownPlus/vendor/erusev/parsedown-extra/ParsedownExtra.php on line 241PHP message: PHP Notice:  Trying to access array offset on value of type null in /var/www/app/plugins/MarkdownPlus/vendor/erusev/parsedown-extra/ParsedownExtra.php on line 241PHP message: PHP Notice:  Trying to access array offset on value of type null in /var/www/app/plugins/MarkdownPlus/vendor/erusev/parsedown-extra/ParsedownExtra.php on line 305" while reading response header from upstream, client: 172.17.0.3, server: localhost, request: "GET /project/4/task/110 HTTP/1.1", upstream: "fastcgi://unix:/var/run/php-fpm.sock:", host: "projects.divdist.com",
[15-Mar-2021 13:53:23 UTC] PHP Warning:  Module 'fileinfo' already loaded in Unknown on line 0,
PHP message: PHP Notice:  Trying to access array offset on value of type null in /var/www/app/plugins/MarkdownPlus/vendor/erusev/parsedown-extra/ParsedownExtra.php on line 241",
PHP message: PHP Notice:  Trying to access array offset on value of type null in /var/www/app/plugins/MarkdownPlus/vendor/erusev/parsedown-extra/ParsedownExtra.php on line 241",
2021/03/15 13:53:25 [error] 16#16: *1 FastCGI sent in stderr: "PHP message: PHP Notice:  Trying to access array offset on value of type null in /var/www/app/plugins/MarkdownPlus/vendor/erusev/parsedown-extra/ParsedownExtra.php on line 241PHP message: PHP Notice:  Trying to access array offset on value of type null in /var/www/app/plugins/MarkdownPlus/vendor/erusev/parsedown-extra/ParsedownExtra.php on line 241" while reading response header from upstream, client: 172.17.0.3, server: localhost, request: "GET /project/4/task/110 HTTP/1.1", upstream: "fastcgi://unix:/var/run/php-fpm.sock:", host: "projects.divdist.com",
PHP message: PHP Notice:  Trying to access array offset on value of type null in /var/www/app/plugins/MarkdownPlus/vendor/erusev/parsedown-extra/ParsedownExtra.php on line 241",
PHP message: PHP Notice:  Trying to access array offset on value of type null in /var/www/app/plugins/MarkdownPlus/vendor/erusev/parsedown-extra/ParsedownExtra.php on line 241",
2021/03/15 13:53:48 [error] 16#16: *18 FastCGI sent in stderr: "PHP message: PHP Notice:  Trying to access array offset on value of type null in /var/www/app/plugins/MarkdownPlus/vendor/erusev/parsedown-extra/ParsedownExtra.php on line 241PHP message: PHP Notice:  Trying to access array offset on value of type null in /var/www/app/plugins/MarkdownPlus/vendor/erusev/parsedown-extra/ParsedownExtra.php on line 241" while reading response header from upstream, client: 172.17.0.3, server: localhost, request: "GET /project/4/task/110 HTTP/1.1", upstream: "fastcgi://unix:/var/run/php-fpm.sock:", host: "projects.divdist.com",
PHP message: PHP Notice:  Trying to access array offset on value of type null in /var/www/app/plugins/MarkdownPlus/vendor/erusev/parsedown-extra/ParsedownExtra.php on line 241",
PHP message: PHP Notice:  Trying to access array offset on value of type null in /var/www/app/plugins/MarkdownPlus/vendor/erusev/parsedown-extra/ParsedownExtra.php on line 241",
2021/03/15 15:20:59 [error] 16#16: *200 FastCGI sent in stderr: "PHP message: PHP Notice:  Trying to access array offset on value of type null in /var/www/app/plugins/MarkdownPlus/vendor/erusev/parsedown-extra/ParsedownExtra.php on line 241PHP message: PHP Notice:  Trying to access array offset on value of type null in /var/www/app/plugins/MarkdownPlus/vendor/erusev/parsedown-extra/ParsedownExtra.php on line 241" while reading response header from upstream, client: 172.17.0.3, server: localhost, request: "GET /project/4/task/110 HTTP/1.1", upstream: "fastcgi://unix:/var/run/php-fpm.sock:", host: "projects.divdist.com",
PHP message: PHP Notice:  Trying to access array offset on value of type null in /var/www/app/plugins/MarkdownPlus/vendor/erusev/parsedown-extra/ParsedownExtra.php on line 241",
PHP message: PHP Notice:  Trying to access array offset on value of type null in /var/www/app/plugins/MarkdownPlus/vendor/erusev/parsedown-extra/ParsedownExtra.php on line 241",
2021/03/15 15:21:41 [error] 16#16: *202 FastCGI sent in stderr: "PHP message: PHP Notice:  Trying to access array offset on value of type null in /var/www/app/plugins/MarkdownPlus/vendor/erusev/parsedown-extra/ParsedownExtra.php on line 241PHP message: PHP Notice:  Trying to access array offset on value of type null in /var/www/app/plugins/MarkdownPlus/vendor/erusev/parsedown-extra/ParsedownExtra.php on line 241" while reading response header from upstream, client: 172.17.0.3, server: localhost, request: "GET /project/4/task/110 HTTP/1.1", upstream: "fastcgi://unix:/var/run/php-fpm.sock:", host: "projects.divdist.com",`

**Comment by creecros** [comment]
@tomaszstrojny ok, so no errors, and all appears to correctly be parsing...let me know if you see anymore issues.

**Comment by creecros** [comment]
reopen if you find any issues, closing for now.

**Comment by tomaszstrojny** [comment]
Changes in the vendor directory is always a lot of fun :)

Anyway, everything works nice now, thanks!

**Comment by creecros** [comment]
I know, I hated to do it, but really had no choice.
