### ISSUE TITLE
PHP-Warning Messages for invalid Checkbox-Markdown

### ISSUE THREAD

**Issue by wakka90** [creecros/MarkdownPlus#5]
Hi,

thanks for the great Plugin! :)
we are using the latest Kanboard Version 1.2.22 and the latest Plugin for MarkdownPlus installed via PluginManager in Kanboard.

The following example will throw a Warning-Message in Kanboard:

![grafik](https://user-images.githubusercontent.com/95288807/169291381-5655214c-0aa1-4cd5-828e-f5b4efe718d0.png)

The Warning would be displayed anywhere in Kanboard (Description, Comments, etc.) where the error occurs.

We created a Merge Request like this one (https://github.com/creecros/MarkdownPlus/commit/bcff4903f288252fa9562c79ba519f454ac1ab0d) for a quickfix.

Regards.

**Comment by Chaosmeister** [comment]
hey, thanks for the report!

what does the description look like to create the error case?

**Comment by wakka90** [comment]
Hi, here are the entries for the Description.
Using the space will make a difference for checkboxes and will throw the warning message as seen in the screenshot above.

`
[]Test Failure
`

`
[ ] Test OK
`

**Comment by wakka90** [comment]
This is our configuration:

![grafik](https://user-images.githubusercontent.com/95288807/169303635-0e2b079e-7dae-4a74-89fc-f4f1e9e9cc01.png)

**Comment by Chaosmeister** [comment]
ah might be an php 8 thing then.  I'll merge your fix

thanks again for reporting!
