### ISSUE TITLE
Checkboxes don't work

### ISSUE THREAD

**Issue by ScarletBlizzard** [creecros/MarkdownPlus#8]
Hello and thanks for this plugin!
I use Kanboard 1.2.25 with the latest version of MarkdownPlus installed via PluginManager.

When I type `- [ ]` into textfield, I see this:
- [ ]

instead of a checkbox.

**Comment by creecros** [comment]
When I type `- [ ]` into this textfield, you also see this:

- [ ] 

so add some text.

- [ ] now I'm a checkbox.
