### ISSUE TITLE
Bracket ([) in task description results in "500 - Internal server error."

### ISSUE THREAD

**Issue by AgatonSax** [creecros/MarkdownPlus#9]
So if task description has a **[** kanboard/?controller=TaskViewController&action=show&task_id=10 is unaccessible. Bord view is not affected. Also edit from drop-down next to task-id-number works fine.

If I escape the bracket, like so: \[ , or format as code (se below): there's no problem.

\```
[
\```

MarkdownPlus ver: 1.1.1
Kanboard ver: 1.2.25

**Comment by creecros** [comment]
interesting. ill look into it. there are a few more issues with this plugin i have noticed since php 8, and ive had quite an issue updating the vendor libs.

**Comment by AgatonSax** [comment]
Another related(?) issue; typing "v o" or clicking "overview" also results in a 500. Regardless, it seems, of having a bracket in task description or not (as presented above).

**Comment by creecros** [comment]
don't know if i fixed it, but i don't get this issue.
